sudo: required
services: 
  - docker

before_install:
  - docker build -t msirathanarun/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run msirathanarun/react-test npm test -- --coverage

after_success:
  - docker build -t msirathanarun/multi-client ./client
  - docker build -t msirathanarun/multi-nginx ./nginx
  - docker build -t msirathanarun/multi-server ./server
  - docker build -t msirathanarun/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  - docker push msirathanarun/multi-client
  - docker push msirathanarun/multi-nginx
  - docker push msirathanarun/multi-server
  - docker push msirathanarun/multi-worker


